export const menu = [
  {
    icon: 'sitemap',
    title: 'BRANCH MAPPING',
    createPath: '/segmap/create',
    createLabel: 'Create Branch Mapping',
    listPath: '/segmap/list',
    listLabel: 'Branch Mapping List',
    id: 'segmap',
    text: 'Branch Mapping',
  },
  {
    icon: 'map',
    title: 'FORM-TYPE',
    createPath: '/form-type/create',
    createLabel: 'Create Form-Type',
    listPath: '/form-type/list',
    listLabel: 'Form-Type List',
    id: 'formtype',
    text: 'Form Type',
  },
  {
    icon: 'industry',
    title: 'SALE TYPE',
    createPath: '/sale-type/create',
    createLabel: 'Create Sale Type',
    listPath: '/sale-type/list',
    listLabel: 'Sale Type List',
    id: 'saletype',
    text: 'Sale Type',
  },
  {
    icon: "tasks",
    title: 'LEAD SOURCE',
    createPath: '/leadsource/create',
    createLabel: 'Create Lead Source',
    listPath: '/leadsource/list',
    listLabel: 'Lead Source List',
    id: 'leadsource',
    text: 'Lead Source',
  },
  {
    icon: 'percent',
    title: 'M-TAX',
    createPath: '/mtax/create',
    createLabel: 'Create M-Tax',
    listPath: '/mtax/list',
    listLabel: 'M-Tax List',
    id: 'mtax',
    text: 'Muncipal Tax',
  },
  {
    icon: "male",
    title: 'SALES MANAGER',
    createPath: '/salesmanager/create',
    createLabel: 'Create Sales Manager',
    listPath: '/salesmanager/list',
    listLabel: 'Sales Manager List',
    id: 'salesmanager',
    text: 'Sales Manager',
  },
  {
    icon: 'user',
    title: 'TEAM LEADER',
    createPath: '/teamleader/create',
    createLabel: 'Create Team Leader',
    listPath: '/teamleader/list',
    listLabel: 'Team Leader List',
    id: 'teamleader',
    text: 'Team Leader',
  },
  {
    icon: 'users',
    title: 'SALES CONSULTANT',
    createPath: '/salesconsultant/create',
    createLabel: 'Create Sales Consultant',
    listPath: '/salesconsultant/list',
    listLabel: 'Sales Consultant List',
    id: 'salesconsultant',
    text: 'Sales Consultant',
  },
  {
    icon: "building outline",
    title: 'FINANCE BANK',
    createPath: '/financebank/create',
    createLabel: 'Create Finance Bank',
    listPath: '/financebank/list',
    listLabel: 'Finance Bank List',
    id: 'financebank',
    text: 'Finance Bank',
  },
  {
    icon: "suitcase",
    title: 'FINANCE CONSULTANT',
    createPath: '/financeconsultant/create',
    createLabel: 'Create Finance Consultant',
    listPath: '/financeconsultant/list',
    listLabel: 'Finance Consultant List',
    id: 'financeconsultant',
    text: 'Finance Consultant',
  },

  {
    icon: 'hashtag',
    title: 'VOUCHER TYPE NUMBERING',
    createPath: '/vt-num/create',
    createLabel: 'Create Voucher Type',
    listPath: '/vt-num/list',
    listLabel: 'Voucher Type List',
    id: 'vtnum',
    text: 'Voucher Type',
  },
  {
    icon: 'globe',
    title: 'CI FORM',
    createPath: '/ciform/create',
    createLabel: 'Create CI Form',
    listPath: '/ciform/list',
    listLabel: 'CI Form List',
    id: 'ciform',
    text: 'CI  Form',
  }

]